export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_LOADING_CANCEL = 'AUTH_LOADING_CANCEL';
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';

export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const RESEND_EMAIL = 'RESEND_EMAIL';
export const RESEND_EMAIL_FAILURE = 'RESEND_EMAIL_FAILURE';
export const VERIFY_EMAIL_ERROR = 'VERIFY_EMAIL_ERROR';
export const VERIFY_EMAIL_ERROR_ASK_AGAIN = 'VERIFY_EMAIL_ERROR_TRY_AGAIN';

export const RESET_PASSWORD_LOADING = 'RESET_PASSWORD_LOADING';
export const RESET_PASSWORD_LOADING_CANCEL = 'RESET_PASSWORD_LOADING_CANCEL';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_ERROR';
export const SEND_EMAIL_UPDATE_PASSWORD_ERROR = 'SEND_EMAIL_UPDATE_PASSWORD_ERROR';
export const SEND_EMAIL_UPDATE_PASSWORD = 'SEND_EMAIL_UPDATE_PASSWORD';
export const VERIFY_REQUEST_PASSWORD = 'VERIFY_REQUEST_PASSWORD';
export const VERIFY_REQUEST_PASSWORD_FAILURE = 'VERIFY_REQUEST_PASSWORD_FAILURE';


